### ISSUE TITLE
soundlab

### ISSUE THREAD

**Issue by ri0t** [c-base/soundlab#18]
_From @ri0t on June 24, 2014 15:55_

We could clear up and improve some things in the soundlab. Namely:
- [x] dehumidify and seal walls (external)
- [ ] ~~Add ventilation~~
- [x] Repair lights, mount lights (esp. a very bright neon cleaning light central in every room)
- [ ] ~~Sundry the storage cabinet on a hot day~~
- [x] Find a new place for cabinet
- [x] Fix the multicore cable (currently on the rear desk@control room)
- [x] Bring order into the control room
- [ ] ~~resize & mount the second glass shield~~

_Copied from original issue: c-base/meta#33_

**Comment by ajuvo** [comment]
what about the ventilation issue? without proper ventilation, much effort is at risk to be in vain. lets get the whole perspective before doing things that go beyond the obvious needs (e.g. trash removal, mold extinction, dust removal).

**Comment by dvzrv** [comment]
@ajuvo very much agreed upon that. It's one of the topics for the soundlab meeting.

**Comment by berlincount** [comment]
I'm really really wary of the whole condensation issue in this context. If you bring warm water into a cold room, the water WILL condense. Raising the air tempature doesn't make a difference, and raising the wall temperature is very hard to do.

Every single expert I've talked to (both from the facility manager and the company that dried the room originally) said the same, ventilation as we think of might be extremely counterproductive.

If we do it, it should be done professionally and with professional planning - the financial resources of c-base itself are very limited in that regard right now.

**Comment by ri0t** [comment]
Moved ventilation to another issue (#4)
